#Name of the workflow
name: CI Demo Workflow
#When to run the workflow
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
#What jobs to run in the workflow
jobs:
  demo-job:
    #Where to run the job
    runs-on: ubuntu-latest

    steps:
        #Step 1: Checkout the repository
      - name: Checkout repository
      #Version of the checkout action to use
        uses: actions/checkout@v3
        #Step 2: Run a demo command
      - name: Run demo command
      #Command to run
        run: echo "Hello, CI is running"